
USER_NAME     =  takahiroitou
PROJECT_NAME  =  pbspro-centos
PACKAGE_NAME  =  ${USER_NAME}/${PROJECT_NAME}
PACKAGE_TAG   =  7

DOCKER_CMD    =  docker

DEPS          =  .deps
SOURCE_DIR    =  .

CHKIMG        =  ../common/chkimg

include  ../common/makefile/Common.mak
